name: CI/CD

on:
  push:
    branches: [ production ]
    paths: 
      - "apps/bank-webhook/**" 
      - "packages/db/**" 
      - "packages/schemas/**" 

jobs:
  deploy-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      # Login to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build
      - name: Build Bank Webhook
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bank-webhook:latest -f apps/bank-webhook/Dockerfile .

      # Push
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bank-webhook:latest

      # Deploy via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/bank-webhook:latest
            
            docker run --rm \
              -e DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/bank-webhook:latest \
              pnpm --filter=@powerpaywallet/db migrate deploy
              
            docker stop bank-webhook || true && docker rm bank-webhook || true

            docker run -d --name bank-webhook \
              -p 3002:3002 \
              -e PORT=3002 \
              -e WEBHOOK_SECRET=${{ secrets.BANK_WEBHOOK_SECRET }} \
              -e DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL}} \
              ${{ secrets.DOCKER_USERNAME }}/bank-webhook:latest
